/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laundry;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Laundryku extends javax.swing.JFrame {

    /**
     * Creates new form Laundryku
     */
    public Laundryku() {
        initComponents();
    }
    public int Total_Harga;
    
    public void reset(){
        combo_jenis.setSelectedItem("Pilih Jenis");
        txt_harga.setText("");
        txt_berat.setText("");
        txt_ttlHarga.setText("");
        txt_bayar.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        txt_ttlHarga = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        btn_setuju = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laundry A&W");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 60));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("   Berat");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 40));

        combo_jenis.setBackground(new java.awt.Color(204, 204, 204));
        combo_jenis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Paket", "Cuci Basah", "Cuci Kering", "Cuci Setrika" }));
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        jPanel1.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 220, 40));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("   Paket");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 40));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("  Bayar");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 40));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("   Harga");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 40));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("   Paket");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 40));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("   Total Harga");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 40));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 40));

        txt_ttlHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ttlHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ttlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 220, 40));

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 220, 40));

        txt_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_beratActionPerformed(evt);
            }
        });
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        jPanel1.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 220, 40));

        btn_setuju.setBackground(new java.awt.Color(204, 204, 204));
        btn_setuju.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_setuju.setText("Setuju");
        btn_setuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setujuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_setuju, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 120, 50));

        btn_batal.setBackground(new java.awt.Color(204, 204, 204));
        btn_batal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 120, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 500);

        setSize(new java.awt.Dimension(533, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_ttlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttlHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ttlHargaActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_beratActionPerformed

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        if (combo_jenis.getSelectedItem().equals("Pilih Jenis")) {
            txt_harga.setText("0");
        } else if (combo_jenis.getSelectedItem().equals("Cuci Basah")) {
            txt_harga.setText("7000");
        } else if (combo_jenis.getSelectedItem().equals("Cuci Kering")) {
            txt_harga.setText("20000");
        } else if (combo_jenis.getSelectedItem().equals("Cuci Setrika")) {
            txt_harga.setText("10000");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        if (txt_berat.getText().equals("")) {
            txt_ttlHarga.setText("0");
        } else {
            int harga = Integer.parseInt(txt_harga.getText());
            int berat = Integer.parseInt(txt_berat.getText());
            Total_Harga = harga * berat;
            txt_ttlHarga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_beratKeyReleased

    private void btn_setujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setujuActionPerformed
        if(txt_harga.getText().isEmpty()||txt_berat.getText().isEmpty()||txt_ttlHarga.getText().isEmpty()||txt_bayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data harus diisi");
        }else{
            int bayar = Integer.parseInt(txt_bayar.getText());
            int kembalian = bayar-Total_Harga;
            JOptionPane.showMessageDialog(null, "Kembalian anda :\n"+kembalian);
            reset();
        }
    }//GEN-LAST:event_btn_setujuActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        reset();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laundryku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laundryku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laundryku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laundryku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laundryku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_setuju;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_ttlHarga;
    // End of variables declaration//GEN-END:variables
}
